import { type NextPage } from "next";
import Head from "next/head";
import HabitItem from "../components/HabitItem";
import NoteItem from "../components/NoteItem";
import TaskItem from "../components/TaskItem";
import { PlusIcon } from '@heroicons/react/24/solid';
import Heading from "../components/Heading";
import TaskList from "../components/TaskList";
import NotesList from "../components/NotesList";

// import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";

const User = {
  user: "Chad",
  userId: 12345,
  Tasks: [
    {
      name: "Start a project",
      id: 1,
      date: "1/17/2023",
      complete: false,
      note: "hello, this is a note",
      tag: "Work",
      tagColor: "bg-red-100",
      assigned: false
    },
    {
      name: "Do the dishes",
      id: 2,
      date: "1/17/2023",
      complete: false,
      note: "hello, this is a note",
      tag: "Home",
      tagColor: "bg-blue-100",
      assigned: false
    },
    {
      name: "Meal Prep",
      id: 3,
      date: "1/17/2023",
      complete: false,
      note: "hello, this is a note",
      tag: "Home",
      tagColor: "bg-blue-100",
      assigned: false
    },
  ],
  Notes: [
    {
      name: "Meeting notes",
      id: 1,
      date: "1/17/2023",
      note: "hello, this is a note",
      tag: "Work",
      tagColor: "bg-red-100",
    },
    {
      name: "Home project notes",
      id: 2,
      date: "1/17/2023",
      note: "hello, this is a note",
      tag: "Home",
      tagColor: "bg-blue-100",
    },
    {
      name: "How to improve skills",
      id: 3,
      date: "1/17/2023",
      note: "hello, this is a note",
      tag: "Work",
      tagColor: "bg-red-100",
    }
  ],
}

const Home: NextPage = () => {
  const { data: tasks, isLoading } = api.task.getAll.useQuery()
  const { data: session, status } = useSession();

  if (status === "loading") {
    return <main>Loading...</main>;
  }

  console.log(tasks)

  console.log(User)
  return (
    <div className="p-3">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css"></link>
      </Head>
      <div className="max-w-screen-lg">
        <Heading headingText={`Welcome ${User.user}`}/>
        <div className="md:flex md:justify-between md:space-x-5">
          {session ? (
            <>
             <TaskList titleText="Unassigned Tasks" tasks={tasks} />
             <NotesList titleText="Note Archive" notes={User.Notes} />
             <button onClick={() => signOut()}>
              Logout
            </button>
            </>
          ) : (
            <button onClick={() => signIn("discord")}>Login with Discord</button>
          )}
        </div>
      </div>
    </div> 
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined },
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
